name: QubesOS RPMs

on:
  push:
    branches:
      - 'intel-txt-aem*'
      - 'xen-uefi'
    tags:
      - '**'
      - '!v*-rc*'

jobs:
  qubes-dom0-package:
    uses: TrenchBoot/.github/.github/workflows/qubes-dom0-packagev2.yml@master
    with:
      qubes-component: 'grub2'
      qubes-pkg-src-dir: '.'
      qubes-pkg-version: '2.13'
