name: Test build and package QubesOS RPMs

on:
  push:
    branches:
      - 'intel-txt-aem*'
    tags:
      - '*'

jobs:
  qubes-dom0-package:
    uses: TrenchBoot/.github/.github/workflows/qubes-dom0-package.yml@master
    with:
      base-commit: '594fe4760a33158e7cd500825ee26a0c9aef5f6b'
      patch-start: 1120
      qubes-component: 'grub2'
      spec-pattern: '/^Patch1119:/'
