name: Build the last successful automatic rebase of tb-dev branch

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: >
          Set this input to do a dry run without building the packages to test
          the rebase.
        required: false
        type: boolean
        default: false
  schedule:
    - cron: '0 0 * * 6'

concurrency:
  group: automatic-rebase

jobs:
  run:
    uses: TrenchBoot/.github/.github/workflows/qubes-derivative-rebase-and-publish.yml@v1
    secrets:
      rebase-token:     ${{ secrets.TRENCHBOOT_REBASE_TOKEN }}
      woodpecker-token: ${{ secrets.WOODPECKER_TOKEN }}
    with:
      source-repo:         TrenchBoot/grub
      downstream-branch:   tb-dev
      pkg-repo:            QubesOS/qubes-grub2
      upstream-url:        https://gitlab.freedesktop.org/gnu-grub/grub.git
      upstream-tag-format: 'grub-%s'
      pkg-spec-in:         grub2.spec.in
      qubes-component:     grub2
      dry-run: ${{ inputs.dry_run == true }}
